#!/usr/bin/env bash
set -euo pipefail
# Fast runtime configuration of the deployed DigSig app.
#
# Writes arduino/python/runtime.env (loaded by config.py, values take precedence
# over the environment), syncs it to the board and restarts the app. Solves the
# "the laptop IP keeps changing" problem: with no argument this machine's LAN IP
# is auto-detected and set as CMS_URL.
#
# Usage:
#   ./cli/configure.sh                     # auto-detect IP -> CMS_URL, keep the rest
#   ./cli/configure.sh --ip 192.168.1.50   # set the CMS host explicitly
#   ./cli/configure.sh --port 8000         # API port (default 8000)
#   ./cli/configure.sh KEY=VALUE ...       # set any keys, e.g. TRIGGER_MODE=timer
#   ./cli/configure.sh --show              # print the current runtime.env
#   ./cli/configure.sh --no-restart        # write + sync, but don't restart

# shellcheck source=cli/_common.sh
source "$(dirname "${BASH_SOURCE[0]}")/_common.sh"

ENV_FILE="$REPO_ROOT/arduino/python/runtime.env"
XMPL_FILE="$REPO_ROOT/arduino/python/runtime.env.xmpl"
KNOWN_KEYS=(CMS_URL POOL_ID SELECTOR_MODE AUDIENCE_MODE AUDIENCE_GROUP AUDIENCE_MODEL_DIR \
            TRIGGER_MODE ENABLE_CAMERA TIMER_INTERVAL_SEC PERSON_DEBOUNCE_SEC DEBUG)

# detect_ip() comes from _common.sh (source IP of the default route = the LAN IP
# the board uses to reach us).

declare -A CFG
load_into_cfg() {  # read a file; later calls override earlier ones.
  local f="$1" line k v
  [[ -f "$f" ]] || return 0
  while IFS= read -r line || [[ -n "$line" ]]; do
    line="${line%%$'\r'}"
    [[ -z "$line" || "$line" == \#* || "$line" != *=* ]] && continue
    k="${line%%=*}"; v="${line#*=}"; k="${k// /}"
    [[ -n "$k" ]] && CFG["$k"]="$v"
  done < "$f"
}

# Default: the board reaches the API via the Caddy reverse proxy (Caddy listens
# on port 80 and forwards $CMS_PATH -> uvicorn:8000, stripping the prefix). No
# port -> port 80. --port N forces direct access on :N.
CMS_PATH="${CMS_PATH:-/digsig}"
PORT=""; IP=""; RESTART=1; SHOW=0
declare -a KV=()
while [[ $# -gt 0 ]]; do
  case "$1" in
    --ip)         IP="$2"; shift 2 ;;
    --port)       PORT="$2"; shift 2 ;;
    --no-restart) RESTART=0; shift ;;
    --show)       SHOW=1; shift ;;
    -h|--help)    sed -n '2,20p' "$0"; exit 0 ;;
    *=*)          KV+=("$1"); shift ;;
    *)            echo "Unknown argument: $1" >&2; exit 1 ;;
  esac
done

if [[ $SHOW -eq 1 ]]; then
  [[ -f "$ENV_FILE" ]] && cat "$ENV_FILE" || echo "(no runtime.env — defaults from config.py are active)"
  exit 0
fi

# Use existing values as the base (template -> current file), then overrides.
load_into_cfg "$XMPL_FILE"
load_into_cfg "$ENV_FILE"

# Set CMS_URL automatically, unless passed explicitly as KEY=VALUE.
explicit_cms=0
for kv in "${KV[@]:-}"; do [[ "$kv" == CMS_URL=* ]] && explicit_cms=1; done
if [[ $explicit_cms -eq 0 ]]; then
  [[ -z "$IP" ]] && IP="$(detect_ip)"
  [[ -z "$IP" ]] && { echo "ERROR: LAN IP not detected — please pass --ip." >&2; exit 1; }
  if [[ -n "$PORT" ]]; then
    CFG[CMS_URL]="http://$IP:$PORT$CMS_PATH"   # direct access (bypasses Caddy)
  else
    CFG[CMS_URL]="http://$IP$CMS_PATH"          # via Caddy on port 80
  fi
fi
for kv in "${KV[@]:-}"; do
  [[ -z "$kv" ]] && continue
  CFG["${kv%%=*}"]="${kv#*=}"
done

{
  echo "# Auto-generated by cli/configure.sh — loaded by arduino/python/config.py."
  echo "# Values take precedence over the environment. Editable by hand; then 'rsync push' + restart."
  for k in "${KNOWN_KEYS[@]}"; do [[ -n "${CFG[$k]+x}" ]] && echo "$k=${CFG[$k]}"; done
  for k in "${!CFG[@]}"; do
    case " ${KNOWN_KEYS[*]} " in *" $k "*) ;; *) echo "$k=${CFG[$k]}" ;; esac
  done
} > "$ENV_FILE"

echo "wrote: $ENV_FILE  (CMS_URL=${CFG[CMS_URL]:-<unset>})"

check_board
echo "-> syncing to the board ..."
"$CLI_DIR/rsync.sh" push >/dev/null
if [[ $RESTART -eq 1 ]]; then
  echo "-> restarting app ..."
  "$CLI_DIR/control.sh" restart >/dev/null
  echo "done. Board UI: http://${BOARD#*@}:$WEB_UI_PORT"
else
  echo "done (without restart)."
fi
