"""Database migration commands — thin wrapper around Alembic."""
from pathlib import Path

import typer
from alembic import command
from alembic.config import Config

cli = typer.Typer(help="Database / migration commands", no_args_is_help=True)

# api/alembic.ini  (this file is api/app/cli/commands/db.py)
_ALEMBIC_INI = Path(__file__).resolve().parents[3] / "alembic.ini"


def _config() -> Config:
    return Config(str(_ALEMBIC_INI))


@cli.command("upgrade")
def upgrade(revision: str = typer.Argument("head")) -> None:
    """Apply migrations up to REVISION (default: head)."""
    command.upgrade(_config(), revision)


@cli.command("downgrade")
def downgrade(revision: str = typer.Argument("-1")) -> None:
    """Revert migrations down to REVISION (default: one step back)."""
    command.downgrade(_config(), revision)


@cli.command("revision")
def revision(message: str, autogenerate: bool = True) -> None:
    """Create a new migration, autogenerated from model changes by default."""
    command.revision(_config(), message=message, autogenerate=autogenerate)


@cli.command("current")
def current() -> None:
    """Show the currently applied revision."""
    command.current(_config())
